services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - db-tier
  app:
    build: .
    command: bash -c "bundle exec rails s -p 3333 -b '0.0.0.0'"
    ports:
      - "3333:3333"
    depends_on:
      - db
    volumes:
      - .:/apollo
    networks:
      - app-tier
      - db-tier

networks:
  app-tier: {}
  db-tier: {}

